---
# Global Variables

# OPNsense FW1
opnsense_admin_username: corp
opnsense_admin_password: DomainVagrant123#

# Domain settings
root_domain: corp.local
domain_name: corp

secondary_root_domain: secure.local
secondary_domain_name: secure

windows_domain_controller_private_ip: 10.0.1.10
windows_domain_controller_hostname: dc01
windows_domain_controller_fqdn: "{{ windows_domain_controller_hostname }}.{{ root_domain }}"

domain_administrator: Administrator
domain_administrator_password: DomainVagrant123#

# DHCP Settings
dhcp_ip_from: 10.0.1.100
dhcp_ip_to: 10.0.1.150
dhcp_ip_mask: 24
dhcp_lease_duration: 8
dhcp_dns_ip: 10.0.1.10


# Timezone settings
win_timezone: "Coordinated Universal Time" #"Eastern Standard Time"

# Windows Server Settings
# win_local_administrator: Administrator
# win_local_administrator_password: LocalVagrant!"#

# ADCS Settings
adcs_host: adcs01
adcs_common_name: "{{ domain_name }}-adcs-CA"
adcs_cert_authority_password: DomainVagrant123#

# ADCS Web Enrollment Settings
ca_web_enrollment: True

## Monitoring
es_version: 8.x
elastic_stack_version: 8.14.1
es_cluster_name: "monitoring"
es_node_name: "node-1"
es_network_host: "0.0.0.0"
es_port: 9200
elasticsearch_host: "localhost"
elasticsearch_url: "https://{{ elasticsearch_host }}:{{ es_port }}"
elasticsearch_ca_path: /etc/elasticsearch/certs/http_ca.crt

kibana_version: "8.x"
kibana_server_host: "0.0.0.0"
kibana_port: 5601
kibana_host: "localhost"
fleet_port: 8220
fleet_policy_name: "MyFleetPolicy"
fleet_policy_description: "My custom Fleet policy"
policy_settings: 
  #enrollment_token: "your-enrollment-token"  # Get this from Kibana
  elastic_agent_download_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.2-linux-x86_64.tar.gz"
  elastic_agent_version: "8.14.2"
  elastic_agent_install_dir: "/opt" 

logstash_port: 5044

# Winlogbeat
logstash_ip: 10.0.1.250
logstash_winlogbeat_port: 5044
winlogbeat_download_url_base: 'https://artifacts.elastic.co/downloads/beats/winlogbeat'
file_ext: '.zip'
winlogbeat_download_file: 'winlogbeat-8.14.2-windows-x86_64'
winlogbeat_install_location: "C:/Program Files/Winlogbeat"
