# Global Variables

# Domain settings
root_domain: cdojo.local
domain_name: cdojo

windows_domain_controller_private_ip: 10.0.1.10
windows_domain_controller_hostname: dc01
windows_domain_controller_fqdn: "{{ windows_domain_controller_hostname }}.{{ root_domain }}"

domain_administrator: Administrator
domain_administrator_password: DomainVagrant!"#

# DHCP Settings
dhcp_ip_from: 10.0.1.100
dhcp_ip_to: 10.0.1.150
dhcp_ip_mask: 24
dhcp_lease_duration: 8
dhcp_dns_ip: 10.0.1.10


# Timezone settings
win_timezone: "Eastern Standard Time"

# Windows Server Settings
# win_local_administrator: Administrator
# win_local_administrator_password: LocalVagrant!"#


# ADCS Settings
adcs_host: win2019-adcs
adcs_common_name: attacklab-win2019-adcs-CA
adcs_cert_authority_password: Vagrant!"#

# ADCS Web Enrollment Settings
ca_web_enrollment: True

# Ansible WinRM Configuration
ansible_winrm_server_cert_validation: ignore
ansible_winrm_scheme: http
ansible_winrm_transport: basic
ansible_port: 5985