# https://www.faqforge.com/windows/configure-dhcp-powershell/

- name: Install DHCP
  win_feature:
    name: DHCP
    state: present
    include_management_tools: yes
  register: win_feature

- name: Reboot if installing windows feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

- name: allow dhcp in dc
  win_shell: |
    Add-DHCPServerInDC -DNSName {{windows_domain_controller_fqdn}}
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_administrator}}"
    ansible_become_password: "{{domain_admin_password}}"

- name: Set dhcp scope
  win_shell: |
    $s = Get-DhcpServerv4Scope
    if ($null -eq $s) {
      Add-DhcpServerV4Scope -Name "DHCP Scope" -StartRange {{ip_from}} -EndRange {{ip_to}} -SubnetMask {{ip_mask}} -LeaseDuration {{lease_duration}}
    }

- name: Add DNS Server, Router Gateway Options in DHCP
  win_shell: |
    Set-DhcpServerV4OptionValue -DnsServer {{dns_ip}}

- name: Restart service DHCP
  win_service:
    name: 'dhcpserver'
    state: restarted