- name: Install ADCS
  win_feature:
    name: AD-Certificate
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: Install-WindowsFeature ADCS-Cert-Authority
  ansible.windows.win_feature:
    name: ADCS-Cert-Authority
    state: present
    include_management_tools: yes

- name: Install-WindowsFeature ADCS-Web-Enrollment
  ansible.windows.win_feature:
    name: ADCS-Web-Enrollment
    state: present
  when: ca_web_enrollment

- name: Install-ADCSCertificationAuthority-PS
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $domain_administrator,

          [String]
          $domain_administrator_password,

          [String]
          $ca_common_name
      )
      $pass = ConvertTo-SecureString $domain_administrator_password -AsPlainText -Force
      $Cred = New-Object System.Management.Automation.PSCredential ($domain_administrator, $pass)
      try {
        Install-AdcsCertificationAuthority -Credential $Cred -CAType EnterpriseRootCA -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" -KeyLength 2048 -HashAlgorithmName SHA256 -ValidityPeriod Years -ValidityPeriodUnits 5 -CACommonName $ca_common_name -Force
        $Ansible.Changed = $true
      } catch {
        $Ansible.Changed = $false
      }
    error_action: stop
    parameters:
      domain_administrator: "{{domain_administrator}}"
      domain_administrator_password: "{{ domain_administrator_password }}"
      ca_common_name: "{{root_domain}}"

# ESC 8
# ignore error if already installed
- name: Enable Web enrollement
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param ()
      try {
        Install-AdcsWebEnrollment -Force
        $Ansible.Changed = $true
      } catch {
        $Ansible.Changed = $false
      }
  when: ca_web_enrollment

- name: reboot | Rebooting Server
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 15
