---
- block:
  - name: Install Active Directory Certificate Services (AD CS)  

  - ansible.builtin.import_tasks: install_adcs.yml
  - ansible.builtin.import_tasks: create_templates.yml  

  rescue:
    - debug:
        msg: "AD CS installation failed. Check logs for details." 
