elastic_password: "0HteSC8mhMnsClDlzOu_"
kibana_system_password: "ANr=lyVW4bm4qSxBzdFO"
enrollment_token: "eyJ2ZXIiOiI4LjE0LjAiLCJhZHIiOlsiMTAuMC4xLjI1MDo5MjAwIl0sImZnciI6IjY5ZjM3NTViNzQ1NTFkMGEyMDkzYjNiZGUwNzdhNzdmNjY0NjRkMDBlYWY4ODE0ZWI4ZDI2ZGNkOTA0YmQ0NTAiLCJrZXkiOiJ5NXljbkpBQkhDYXptcUszeFlhaTpzT1VqaFRJMFNMR1htcGxYWGNHOFh3In0="