---
- hosts: fw1
  become: yes
  gather_facts: no

  tasks:
    - name: Set hostname
      puzzle.opnsense.system_settings_general:
        hostname: "fw1"

    - name: Add OPNsense user
      puzzle.opnsense.system_access_users:
        username: "{{ opnsense_admin_username }}"
        password: "{{ opnsense_admin_password }}"
        full_name: cdojo
        groups:
          - admins
        state: present
      register: result

    - name: Create WAN assignment
      puzzle.opnsense.interfaces_assignments:
        identifier: "WAN"
        device: "vtnet2"
        description: "wan_interface"

    - name: Create CORP assignment
      puzzle.opnsense.interfaces_assignments:
        identifier: "CORP"
        device: "vtnet3"
        description: "corporate"

    - name: Create BANK assignment
      puzzle.opnsense.interfaces_assignments:
        identifier: "Bank"
        device: "vtnet4"
        description: "bank"

    # - name: Allow all outbound trafic from LAN Network
    #   puzzle.opnsense.firewall_rules:
    #     interface: "LAN"
    #     action: "pass"
    #     direction: "out"
    #     protocol: "any"
    #     description: "Allow all outbound trafic from LAN Network"

    # - name: Allow all outbound trafic from corporate Network
    #   puzzle.opnsense.firewall_rules:
    #     interface: "CORP"
    #     action: "pass"
    #     direction: "out"
    #     protocol: "any"
    #     description: "Allow all outbound trafic from corporate Network"
        
    - name: Remove OPNsense Vagrant user
      puzzle.opnsense.system_access_users:
        username: vagrant
        password: vagrant
        state: absent
      register: result
      
    # - name: Pulling routes
    #   ansibleguy.opnsense.list:
    #     target: 'route'
    #   register: existing_routes
        
