- hosts: fw1
  become: yes
  gather_facts: yes

  # module_defaults:
  #   group/ansibleguy.opnsense.all:
  #     firewall: '192.168.122.191'

  tasks:
    - name: Set hostname
      puzzle.opnsense.system_settings_general:
        hostname: "fw1"

    - name: Add OPNsense user
      puzzle.opnsense.system_access_users:
        username: johndoe
        password: secret
        full_name: John Doe
        email: johndoe@example.com
        groups:
          - admins
        state: present
      register: result

    - name: Create new assignment
      puzzle.opnsense.interfaces_assignments:
        identifier: "LAN"
        device: "vtnet1"
        description: "lan_interface"

    - name: Create new assignment
      puzzle.opnsense.interfaces_assignments:
        identifier: "WAN"
        device: "vtnet2"
        description: "wan_interface"

    - name: Allow all outbound trafic from LAN Network
      puzzle.opnsense.firewall_rules:
        interface: "LAN"
        action: "pass"
        direction: "out"
        protocol: "any"
        description: "Allow all outbound trafic from LAN Network"
    
    # - name: Pulling routes
    #   ansibleguy.opnsense.list:
    #     target: 'route'
    #   register: existing_routes
        
