---
- name: Configure itwrk1 Windwos 10 Client
  hosts: itwrk1
  gather_facts: false


  tasks:
    - name: Configure Windows Firewall
      win_firewall_rule:
        name: Allow RDP
        localport: 3389
        action: allow
        direction: in
        protocol: TCP
        state: present

    - name: Disable Windows Defender (Optional)
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        type: dword
        data: 1

  roles:
    - windows_common
    - windows_domain_clients
    - windows_chocolatey
    - windows_winlogbeat
    - windows_sysmon
    - windows_th_akira
