---
- hosts: metasploitable3-ub1404
  gather_facts: false
  become: true

  tasks:
    - name: Set new hostname
      hostname:
        name: "linux-production-server"

    - name: Update network configuration file
      lineinfile:
        path: /etc/network/interfaces
        regexp: "^iface eth1 inet.*"
        line: "iface eth1 inet static\naddress 10.0.1.50\nnetmask 255.255.255.0\ngateway 10.0.1.254"

    - name: Restart networking
      service:
        name: networking
        state: restarted 
