---
- name: Install web01
  hosts: web01
  gather_facts: false

  tasks:
    - name: Install Web-Server feature
      win_feature:
        name: Web-Server
        state: present

  roles:
    - windows_common
    - windows_domain_clients
    - windows_fileshare