---
- name: Configure Windows 10 Client
  hosts: win10-client
  become: yes

  tasks:

    - name: Install Chocolatey (Package Manager)
      win_chocolatey:
        state: present

    - name: Install Applications with Chocolatey
      win_chocolatey:
        name:
          - googlechrome
          - vscode
          - 7zip
          - adobereader
          # Add more applications as needed

    - name: Apply Windows Updates
      win_updates:
        category:
          - CriticalUpdates
          - SecurityUpdates
        state: installed
        reboot: yes  # Reboot if required after updates

    - name: Configure Windows Firewall
      win_firewall_rule:
        name: Allow RDP
        localport: 3389
        action: allow
        direction: in
        protocol: TCP
        state: present

    - name: Disable Windows Defender (Optional)
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        type: dword
        data: 1

    - name: Set Desktop Background
      win_file:
        path: C:\Windows\Web\Wallpaper\Windows\img0.jpg  # Replace with the desired image path
        state: file
        recurse: yes

    - name: Customize Power Settings (Optional)
      win_power_plan:
        name: High Performance  # Choose the desired power plan