- name: Test WinRM Connection and Gather Facts
  hosts: dc01  
  gather_facts: yes
  tasks:
    - name: Ping the Windows host
      win_ping:

    - name: Gather basic Windows information
      win_command: systeminfo
      register: system_info
  
    - name: Print the gathered information
      debug:
        var: system_info.stdout
