---
- name: Load user data from file
  include_vars:
    file: ../../creation/users.yml
    name: user_data

- name: Load group data from file
  include_vars:
    file: ../../creation/group_data.yml
    name: group_data

- name: Create user account
  microsoft.ad.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    firstname: "{{ item.name.split(' ')[0] }}"
    surname: "{{ item.name.split(' ')[1] | default('') }}"
    upn: "{{ item.name.split(' ')[0] }}.{{ item.name.split(' ')[1] | default('') }}@{{ root_domain }}"
    update_password: always
  until: create_account_result is not failed
  register: create_account_result
  loop: "{{ user_data.users }}"

- name: Create AD groups
  microsoft.ad.group:
    identity: "{{ item.name }}"
    description: "{{ item.description }}"
    scope: global
  loop: "{{ group_data.group_data }}"

# - name: Add members to the group
#   microsoft.ad.group:
#     name: "{{ item.name }}"
#     scope: domainlocal
#     members:
#       add: 
#         - "daniel.smith@corp.local"
#   loop: "{{ group_data.group_data }}"