---
- name: Configure upstream DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - '8.8.8.8'
      - '8.8.4.4'

- name: Be sure DNS feature is installed
  win_feature:
    name: DNS
    state: present

- name: Install RSAT AD Admin Center feature
  win_feature:
    name: RSAT-AD-AdminCenter
    state: present

- name: Install AD Domain Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: Reboot server after installing AD-Domain-Services
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 15
    reboot_timeout: 120

- name: Create a new Windows domain
  microsoft.ad.domain:
    dns_domain_name: "{{ root_domain }}"
    safe_mode_password: "{{ domain_administrator_password }}"
    install_dns: yes
    reboot: yes
  register: domain_install

- name: Reboot server after creating Windows domain if required
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 150
    msg: "Reboot after domain creation"
  when: domain_install.reboot_required

- name: Wait for system to become reachable over WinRM after reboot
  wait_for_connection:
    timeout: 900

- name: Install ActiveDirectory PowerShell module
  win_shell: Install-WindowsFeature RSAT-AD-PowerShell

- name: Add host to domain controller
  microsoft.ad.domain_controller:
    #name: dc01.cdojo.local #"{{ ansible_hostname }}"
    dns_domain_name: "{{ root_domain }}"
    domain_admin_user: "{{ domain_administrator }}@{{ root_domain }}"
    domain_admin_password: "{{ domain_administrator_password }}"
    safe_mode_password: "{{ domain_administrator_password }}"
    state: domain_controller
  register: add_dc_result

- name: Reboot server for domain finalization if required
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 15
    reboot_timeout: 120
  when: add_dc_result.reboot_required

- name: Wait for system to become reachable over WinRM after final reboot
  wait_for_connection:
    timeout: 900

- name: Configure localhost as DNS server
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "127.0.0.1" 

- name: Configure autologon for Domain Administrator
  community.windows.win_auto_logon:
    username: "{{ root_domain }}\\{{ domain_administrator }}"
    password: "{{ domain_administrator_password }}"

- name: Ensure Administrator is part of Enterprise Admins
  win_domain_group_membership:
    name: "Enterprise Admins"
    members:
      - Administrator
    state: present

- name: Ensure Administrator is part of Domain Admins
  win_domain_group_membership:
    name: "Domain Admins"
    members:
      - Administrator
    state: present

- name: Set Domain Administrator Password
  win_user:
    name: Administrator
    password: "{{ domain_administrator_password }}"
    update_password: always