# - name: unconstrained user unconstrained delegation set
#   win_shell: |
#     $user = (Get-ADUser -Identity "Unconstrained.User").DistinguishedName
#     Set-ADAccountControl -Identity $user -TrustedForDelegation $True
#   register: unconstrained_delegation_set

# - name: constrained user set constrained delegation
#   win_shell: |
#     $user = (Get-ADUser -Identity "Constrained.User").DistinguishedName
#     Set-ADObject -Identity $user -Add @{"msDS-AllowedToDelegateTo" = @("CIFS/dc01","CIFS/dc01.{{ root_domain }}","CIFS/dc01.{{ root_domain }}/{{ root_domain }}")}
#   register: constrained_delegation_set


#   Unconstrained Delegation Setting: The first task is setting the TrustedForDelegation property of the user Unconstrained.User to True. This means that the user is trusted to delegate their identity to any service. This is known as “unconstrained delegation”. Here’s the corresponding Ansible code:
# - name: unconstrained user unconstrained delegation set
#   win_shell: |
#     $user = (Get-ADUser -Identity "Unconstrained.User").DistinguishedName
#     Set-ADAccountControl -Identity $user -TrustedForDelegation $True
#   register: unconstrained_delegation_set

# Constrained Delegation Setting: The second task is setting the msDS-AllowedToDelegateTo property of the user Constrained.User. This property is a list of services to which the user can delegate their identity. This is known as “constrained delegation”. Here’s the corresponding Ansible code:
# - name: constrained user set constrained delegation
#   win_shell: |
#     $user = (Get-ADUser -Identity "Constrained.User").DistinguishedName
#     Set-ADObject -Identity $user -Add @{"msDS-AllowedToDelegateTo" = @("CIFS/dc01","CIFS/dc01.{{ root_domain }}","CIFS/dc01.{{ root_domain }}/{{ root_domain }}")}
#   register: constrained_delegation_set

# In both tasks, the register keyword is used to store the output of the tasks in variables (unconstrained_delegation_set and constrained_delegation_set), which can be used later in the playbook.

# Please note that delegation should be used carefully due to its potential security implications. Unconstrained delegation, in particular, is generally not recommended due to its risks. Always follow the principle of least privilege when configuring delegation. Hope this helps! Let me know if you have any other questions.