- name: Disable the user 'vagrant'
  ansible.windows.win_user:
    name: vagrant
    account_disabled: false
  become: yes
  become_method: runas
  become_user: "{{domain_administrator}}"
  vars:
    ansible_become_pass: "{{domain_administrator_password}}"