---
- name: Install dependencies
  apt:
    name: 
      - apt-transport-https
      - gnupg
    state: present
    update_cache: yes
  become: yes

- name: Add Elasticsearch GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  become: yes

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ es_version }}/apt stable main"
    state: present
    update_cache: yes
  become: yes

- name: Install Elasticsearch and Kibana
  apt:
    name: 
      - elasticsearch
      - kibana
    state: present
    update_cache: yes
  become: yes

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart Elasticsearch
  become: yes

- name: Ensure Elasticsearch directories have correct permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0750'
  loop:
    - /etc/elasticsearch
    - /var/lib/elasticsearch
    - /var/log/elasticsearch
  become: yes


- name: Ensure Elasticsearch is started and enabled
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  become: yes

- name: Reset password for elastic user
  shell: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -b -s"
  register: reset_elastic_password
  retries: 3
  delay: 10
  until: reset_elastic_password.rc == 0
  become: yes

- name: Store new elastic password
  set_fact:
    elastic_password: "{{ reset_elastic_password.stdout_lines[-1] }}"

- name: Reset password for kibana_system user
  shell: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -b -s"
  register: reset_kibana_system_password
  retries: 3
  delay: 10
  until: reset_kibana_system_password.rc == 0
  become: yes

- name: Store new kibana_system password
  set_fact:
    kibana_system_password: "{{ reset_kibana_system_password.stdout_lines[-1] }}"

- name: Stop Kibana service if running
  systemd:
    name: kibana
    state: stopped
  become: yes

- name: Ensure Kibana config directory exists with correct permissions
  file:
    path: /etc/kibana
    state: directory
    owner: kibana
    group: kibana
    mode: '0755'
  become: yes

- name: Configure Kibana to use kibana_system user
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  vars:
    kibana_system_password: "{{ kibana_system_password }}"
  notify: Restart Kibana
  become: yes