---
- name: Install Kibana
  become: yes
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Create Kibana keystore
  command: /usr/share/kibana/bin/kibana-keystore create
  args:
    creates: "{{ kibana_config_dir }}/kibana.keystore"
  become: yes

- name: Add SSL certificate and key to Kibana keystore
  command: /usr/share/kibana/bin/kibana-keystore add {{ item.key }} --stdin
  args:
    stdin: "{{ item.value }}"
  loop:
    - { key: "server.ssl.keystore.password", value: "{{ kibana_keystore_password }}" }
    - { key: "elasticsearch.ssl.keystore.password", value: "{{ elasticsearch_keystore_password }}" }
  become: yes
  no_log: true

- name: Copy Elasticsearch CA certificate
  copy:
    content: "{{ elasticsearch_ca_content }}"
    dest: "{{ elasticsearch_ca_path }}"
    owner: kibana
    group: kibana
    mode: '0600'
  become: yes

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  become: yes
  notify: Restart Kibana

- name: Ensure Kibana directories have correct permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: kibana
    group: kibana
    mode: '0750'
  loop:
    - /etc/kibana
    - /var/lib/kibana
    - /var/log/kibana
  become: yes

- name: Ensure Kibana service is started and enabled
  become: yes
  systemd:
    name: kibana
    enabled: yes
    state: started