- name: Create local user account
  win_user:
    name: "{{ domain_administrator }}"  
    password: "{{ domain_administrator_password }}"   
    state: present
    groups:
      - Administrators
      - Remote Desktop Users
  ignore_errors: true
