---
# - name: Get network profile information as JSON
#   win_shell: |
#     Get-NetConnectionProfile | Select-Object -Property Name, NetworkCategory | ConvertTo-Json
#   register: net_profile_json

# - name: Set network profile to Private if currently Public
#   win_shell: |
#     Set-NetConnectionProfile -Name "{{ item.Name }}" -NetworkCategory Private
#   loop: "{{ net_profile_json.stdout | from_json }}"
#   when: item.NetworkCategory == "Public"

# - name: Enable and configure WinRM service
#   win_shell: |
#     winrm quickconfig -q
#     winrm set winrm/config/service/auth @{Basic="true"}
#     winrm set winrm/config/service @{AllowUnencrypted="true"}
#     winrm set winrm/config/winrs @{MaxMemoryPerShellMB="1024"}
#     winrm set winrm/config @{MaxTimeoutms="1800000"}
#     winrm set winrm/config @{MaxConcurrentOperationsPerUser="4294967295"}
#     winrm set winrm/config/service @{EnumerationTimeoutms="240000"}
#     winrm set winrm/config/service @{MaxConnections="4294967295"}
#     winrm set winrm/config/client @{AllowUnencrypted="true"}
#     winrm set winrm/config/client/auth @{Basic="true"}
#   register: winrm_configure

- name: Open WinRM HTTP port in firewall
  win_firewall_rule:
    name: "WinRM HTTP"
    enable: yes
    direction: in
    action: allow
    protocol: TCP
    localport: 5985
