---
- name: Install Logstash
  apt:
    name: "logstash"
    state: present
    update_cache: yes
  become: yes

- name: Configure Logstash
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  become: yes
  notify: Restart Logstash

- name: Create Logstash pipeline configuration
  template:
    src: logstash_pipeline.conf.j2
    dest: /etc/logstash/conf.d/logstash_pipeline.conf
  become: yes
  notify: Restart Logstash

- name: Ensure Logstash directories have correct permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: logstash
    group: logstash
    mode: '0750'
  loop:
    - /etc/logstash
    - /var/lib/logstash
    - /var/log/logstash
  become: yes

- name: Ensure Logstash service is started and enabled
  systemd:
    name: logstash
    enabled: yes
    state: started
  become: yes

- name: Wait for Logstash to start
  wait_for:
    port: "{{ logstash_port }}"
    delay: 10

- name: Ensure Logstash is restarted if configuration changed
  meta: flush_handlers